In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.24.3


In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array(42)

In [8]:
print(arr)

42


In [9]:
arr = np.array([[1,2,3] , [4,5,6]])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [12]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [14]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
arr = np.array([1,2,3,4], ndmin=6)

In [16]:
print(arr)

[[[[[[1 2 3 4]]]]]]


In [17]:
print('number of dimensions :',arr.ndim)

number of dimensions : 6


In [18]:
arr = np.array([1,2,3,4])

In [19]:
print(arr[3])

4


In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [21]:
print('2nd element on 1st dim:', arr[0,1])

2nd element on 1st dim: 2


In [22]:
arr = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [23]:
print(arr[0,1,2])

6


In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [25]:
print('last element from 2nd dim:', arr[1,-1])

last element from 2nd dim: 10


In [26]:
arr = np.array([1,2,3,4,5,6,7])

In [27]:
print(arr[1:5])

[2 3 4 5]


In [28]:
arr = np.array([1,2,3,4,5,6,7])

In [29]:
print(arr[4:])

[5 6 7]


In [30]:
print(arr[:4])

[1 2 3 4]


In [31]:
print(arr[-3:-1])

[5 6]


In [32]:
print(arr[1:5:2])

[2 4]


In [33]:
print(arr[::2])

[1 3 5 7]


In [34]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [35]:
print(arr[1, 1:4])

[7 8 9]


In [36]:
print(arr[0:2, 2])

[3 8]


In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [38]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [39]:
arr = np.array([1,2,3,4])

In [40]:
print(arr.dtype)

int32


In [41]:
arr = np.array(['apple','banana','cherry'])

In [42]:
print(arr.dtype)

<U6


In [44]:
arr = np.array([1,2,3,4], dtype='S')

In [45]:
print(arr)

[b'1' b'2' b'3' b'4']


In [46]:
print(arr.dtype)

|S1


In [47]:
arr = np.array([1,2,3,4], dtype='i4')

In [48]:
print(arr)

[1 2 3 4]


In [49]:
print(arr.dtype)

int32


In [52]:
arr = np.array(['a','2','3'], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [53]:
arr = np.array([1.1, 2.1, 3.1])

In [54]:
newarr = arr.astype('i')

In [55]:
print(newarr)

[1 2 3]


In [56]:
print(newarr.dtype)

int32


In [57]:
arr = np.array([1,0,3])

In [58]:
newarr = arr.astype(bool)

In [59]:
print(newarr)

[ True False  True]


In [60]:
print(newarr.dtype)

bool


In [61]:
arr = np.array([1,2,3,4,5])

In [62]:
x = arr.copy()

In [63]:
arr[0]=42

In [64]:
print(arr)

[42  2  3  4  5]


In [65]:
print(x)

[1 2 3 4 5]


In [66]:
x = arr.view()

In [67]:
arr[0] = 42

In [68]:
print(arr)

[42  2  3  4  5]


In [69]:
print(x)

[42  2  3  4  5]


In [70]:
x = arr.view()

In [71]:
x[0] = 31

In [72]:
print(arr)

[31  2  3  4  5]


In [73]:
print(x)

[31  2  3  4  5]


In [78]:
arr = np.array([1,2,3,4,5])

In [79]:
x= arr.copy()

In [80]:
y= arr.view()

In [81]:
print(x.base)

None


In [82]:
print(y.base)

[1 2 3 4 5]


In [83]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [84]:
print(arr.shape)

(2, 4)


In [92]:
arr = np.array([1,2,3,4], ndmin=5)

In [93]:
print(arr)

[[[[[1 2 3 4]]]]]


In [94]:
print('shape of array:', arr.shape)

shape of array: (1, 1, 1, 1, 4)


In [95]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [96]:
newarr = arr.reshape(4,3)

In [97]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [98]:
newarr = arr.reshape(2,3,2)

In [99]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [100]:
arr = np.array([1,2,3,4,5,6,7,8])

In [101]:
newarr = arr.reshape(2,2,-1)

In [102]:
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
arr = np.array([[1,2,3],[4,5,6]])

In [108]:
newarr = arr.reshape(-1)

In [109]:
print(newarr)

[1 2 3 4 5 6]


In [111]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [112]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [113]:
arr = np.array([[1,2,3], [4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [114]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [116]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [117]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [118]:
arr = np.array([1,2,3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [119]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [121]:
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [122]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [123]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [124]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [125]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr= np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [126]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [128]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [133]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
