In [2]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

In [8]:
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [10]:
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [12]:
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [13]:
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [14]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [16]:
arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [17]:
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [18]:
arr = np.array([6,7,8,9])
x= np.searchsorted(arr, 7)
print(x)

1


In [19]:
x= np.searchsorted(arr, 7, side='right')
print(x)

2


In [20]:
arr = np.array([1,3,5,7])
x= np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [21]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [24]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [26]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [27]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [28]:
arr = np.array([41, 42, 43, 44])
x= [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [29]:
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
            filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [30]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = []
for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
            filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [31]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [32]:
arr = np.array([1,2,3,4,5,6,7])
filter_arr = arr % 2 ==0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [33]:
from numpy import random


In [36]:
x= random.randint(100)
print(x)

15


In [37]:
x = random.rand()
print(x)

0.32238805909512613


In [39]:
x = random.randint(100, size=(5))
print(x)

[10 54 56 16  7]


In [40]:
x= random.randint(100, size=(3,5))
print(x)

[[46 33 79 60  2]
 [78 46 43 12 62]
 [85 24 73 59 12]]


In [41]:
x= random.rand(5)
print(x)

[0.08227822 0.35522068 0.99525654 0.43484059 0.1602939 ]


In [42]:
x= random.rand(3,5)
print(x)

[[0.34663573 0.16661491 0.38587992 0.33621463 0.96752286]
 [0.41041885 0.34099546 0.96052965 0.22069477 0.6312629 ]
 [0.85177699 0.29702331 0.14178505 0.17306587 0.97323202]]


In [44]:
x = random.choice([3,5,7,9])
print(x)

7


In [45]:
x= random.choice([3,5,7,9], size=(3,5))
print(x)

[[3 3 5 3 5]
 [3 9 5 3 5]
 [3 7 7 9 9]]


In [46]:
x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(100))
print(x)

[7 7 5 5 7 7 5 7 5 7 7 5 5 7 7 7 5 7 3 5 7 7 5 3 5 7 7 5 5 7 3 7 7 3 5 7 3
 5 5 3 5 7 7 7 7 5 7 5 5 7 3 5 7 5 5 3 7 7 5 7 7 3 7 5 7 7 5 3 3 3 7 7 7 5
 5 5 7 7 5 7 7 7 7 7 7 5 3 7 5 7 7 7 5 7 3 7 5 7 5 7]


In [47]:
x = [1,2,3,4]
y = [4,5,6,7]
z = []
for i, j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [48]:
z= np.add(x,y)
print(z)

[ 5  7  9 11]


In [49]:
def myadd(x, y):
    return x+y
myadd = np.frompyfunc(myadd, 2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [50]:
import numpy as np

In [51]:
print(type(np.add))

<class 'numpy.ufunc'>


In [52]:
print(type(np.concatenate))

<class 'function'>


In [53]:
if type(np.add)==np.ufunc:
    print('add is ufunc')
else:
    print('add is not func')

add is ufunc


In [54]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [56]:
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10 -10 -10 -10 -10 -10]


In [57]:
newarr = np.multiply(arr1, arr2)
print(newarr)

[200 231 264 299 336 375]


In [59]:
arr1 = np.array([10, 20, 30,40,50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [60]:
newarr = np.power(arr1, arr2)
print(newarr)

[      1000    3200000  716276736 -520093696       2500          0]


In [61]:
newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  0  0  0  0 27]


In [63]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3,7,9,8,2,33])
newarr = np.divmod(arr1, arr2)
print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [65]:
arr = np.array([-1,-2,1,2,3,-4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [67]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [68]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [69]:
arr = np.around(3.1666, 2)
print(arr)

3.17


In [70]:
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [71]:
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


In [72]:
arr = np.arange(1,10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [73]:
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
