In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [4]:
from math import log

In [5]:
nplog = np.frompyfunc(log, 2,1)

In [6]:
print(nplog(100, 15))

1.7005483074552052


In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
newarr = np.add(arr1, arr2)
print(newarr)

[2 4 6]


In [8]:
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [9]:
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[6 6]


In [10]:
arr = np.array([1,2,3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


In [11]:
arr = np.array([1,2,3,4])
x= np.prod(arr)
print(x)

24


In [12]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
x = np.prod([arr1, arr2])
print(x)

40320


In [13]:
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [14]:
arr = np.array([5,6,7,8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


In [15]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [16]:
newarr = np.diff(arr, n=2)
print(newarr)

[  5 -30]


In [17]:
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

12


In [18]:
arr = np.array([3,6,9])
x= np.lcm.reduce(arr)
print(x)

18


In [19]:
arr = np.arange(1,11)
x= np.lcm.reduce(arr)
print(x)

2520


In [20]:
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)

3


In [21]:
arr = np.array([20, 8, 32, 36, 16])
x= np.gcd.reduce(arr)
print(x)

4


In [22]:
x = np.sin(np.pi/2)
print(x)

1.0


In [23]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [24]:
arr = np.array([90, 180, 270, 360])
x= np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [25]:
arr = np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
x=np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [26]:
x= np.arcsin(1.0)
print(x)

1.5707963267948966


In [27]:
arr = np.array([1, -1, 0.1])
x= np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [28]:
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0


In [29]:
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [30]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5 ])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [31]:
x = np.arcsinh(1.0)
print(x)

0.881373587019543


In [32]:
arr = np.array([0.1,  0.2, 0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


In [33]:
arr = np.array([1,1,1,2,3,4,5,5,6,7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [34]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


In [35]:
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


In [37]:
set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]
